import React from 'react';
import {
  AbsoluteFill,
  Audio,
  useCurrentFrame,
  useVideoConfig,
  interpolate,
  Sequence,
  staticFile
} from 'remotion';
import { BrainMascot } from './Character/BrainMascot';
import { TikTokCaptions } from './TikTokCaptions';
import { MedicalQuestionCard } from './MedicalQuestionCard';
import MemeOverlay from './MemeOverlay';
import timestampsData from '../assets/audio/desquamative-aligned-timestamps.json';
import memePlacements from '../assets/memes/desquamative-meme-placements.json';

export const DesquamativeAd = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // Audio timing (with 2x playback - faster, more engaging)
  const PLAYBACK_RATE = 2.0;

  // Duration: 128.68s → 64.34s at 2x → 1931 frames
  const durationInFrames = 1931;

  // Key timestamps from audio:
  // "Think" = 63.18s
  // "A." = 70.69s
  const questionStartTime = 63.18; // Start of "Think about it"
  const answerRevealTime = 70.69; // Start of "A."

  // Convert to frames with playback speed adjustment
  const questionStartFrame = Math.floor((questionStartTime / PLAYBACK_RATE) * fps);
  const answerRevealFrame = Math.floor((answerRevealTime / PLAYBACK_RATE) * fps);
  const timerDuration = answerRevealFrame - questionStartFrame;

  // Question data
  const questionData = {
    "card_id": 1,
    "vignette": "A 42-year-old woman with a 25-pack-year smoking history presents with 4 months of progressive dyspnea and dry cough. She denies occupational exposures. Physical exam shows digital clubbing but no crackles. CT shows bilateral ground-glass opacities with minimal honeycombing. Bronchoalveolar lavage shows numerous pigmented macrophages.",
    "lab_values": [
      {
        "label": "FVC:",
        "value": "72% predicted",
        "status": "elevated",
        "color": "#fbbf24",
        "note": "(normal: >80%)"
      },
      {
        "label": "FEV1/FVC:",
        "value": "0.82",
        "status": "normal",
        "color": "#10b981",
        "note": "(normal: >0.70)"
      },
      {
        "label": "Smoking status:",
        "value": "Active",
        "status": "critical",
        "color": "#ef4444",
        "note": ""
      }
    ],
    "question_text": "What histologic finding will MOST likely improve with smoking cessation and corticosteroids?",
    "options": [
      {
        "letter": "A",
        "text": "Alveolar spaces filled with pigmented macrophages",
        "is_correct": true
      },
      {
        "letter": "B",
        "text": "Fibroblastic foci with temporal heterogeneity",
        "is_correct": false
      },
      {
        "letter": "C",
        "text": "Peribronchiolar pigmented macrophages only",
        "is_correct": false
      },
      {
        "letter": "D",
        "text": "Uniform interstitial fibrosis without honeycombing",
        "is_correct": false
      },
      {
        "letter": "E",
        "text": "Noncaseating granulomas with Langerhans cells",
        "is_correct": false
      }
    ],
    "correct_answer": "A"
  };

  const audioPath = staticFile('assets/audio/desquamative-narration.mp3');

  return (
    <AbsoluteFill style={{ backgroundColor: '#0a0a0a' }}>
      {/* Audio narration - 2x speed (faster, more engaging) */}
      <Audio src={audioPath} playbackRate={PLAYBACK_RATE} />

      {/* Whoosh sound effect at start */}
      <Sequence from={0}>
        <Audio src={staticFile('assets/sfx/whoosh.mp3')} volume={0.4} />
      </Sequence>

      {/* Timer ticking sound - starts at "Think about it", stops before "It's A" */}
      <Sequence from={questionStartFrame} durationInFrames={timerDuration}>
        <Audio src={staticFile('assets/sfx/timer-ticking.mp3')} volume={0.3} />
      </Sequence>

      {/* Correct answer ding - when he says "It's A" */}
      <Sequence from={answerRevealFrame}>
        <Audio src={staticFile('assets/sfx/correct-answer.mp3')} volume={0.6} />
      </Sequence>

      {/* Dr. Synapse - CENTER TOP (uses timestamps for word-sync animation) */}
      <BrainMascot
        audioPath={audioPath}
        position="top-center"
        size={350}
        timestampsSource="desquamative"
        playbackRate={PLAYBACK_RATE}
      />

      {/* Medical Question Card - HTML rendered, not image! (Perfect template spacing) */}
      <MedicalQuestionCard questionData={questionData} />

      {/* TikTok-style captions - line by line at bottom (slightly lower) */}
      <TikTokCaptions
        words={timestampsData}
        playbackRate={PLAYBACK_RATE}
        bottomOffset={320}
      />

      {/* Meme Overlays - Auto-generated by Agent 6 */}
      {memePlacements.memes && memePlacements.memes.map((meme, index) => (
        <MemeOverlay
          key={index}
          memeId={meme.id}
          timestamp={meme.timestamp}
          durationInFrames={meme.duration_frames}
          position={meme.position}
          scale={meme.scale}
          playbackRate={PLAYBACK_RATE}
          overlayText={meme.overlay_text}
        />
      ))}

      {/* Countdown Timer - Circular clock in top right corner */}
      <Sequence from={questionStartFrame} durationInFrames={timerDuration}>
        <div style={{
          position: 'absolute',
          top: 100,
          right: 60,
          zIndex: 150,
        }}>
          {(() => {
            const secondsLeft = Math.max(0, Math.ceil((timerDuration - (frame - questionStartFrame)) / fps));
            const progress = Math.max(0, Math.min(1, (frame - questionStartFrame) / timerDuration));
            const circumference = 2 * Math.PI * 45; // radius = 45
            const offset = circumference * (1 - progress);

            return (
              <div style={{
                position: 'relative',
                width: 120,
                height: 120,
              }}>
                {/* SVG Circle Timer */}
                <svg width="120" height="120" style={{ transform: 'rotate(-90deg)' }}>
                  {/* Background circle */}
                  <circle
                    cx="60"
                    cy="60"
                    r="45"
                    fill="none"
                    stroke="rgba(147, 51, 234, 0.2)"
                    strokeWidth="8"
                  />
                  {/* Progress circle */}
                  <circle
                    cx="60"
                    cy="60"
                    r="45"
                    fill="none"
                    stroke="url(#gradient)"
                    strokeWidth="8"
                    strokeDasharray={circumference}
                    strokeDashoffset={offset}
                    strokeLinecap="round"
                  />
                  {/* Gradient definition */}
                  <defs>
                    <linearGradient id="gradient" x1="0%" y1="0%" x2="100%" y2="100%">
                      <stop offset="0%" stopColor="#9333ea" />
                      <stop offset="100%" stopColor="#db2777" />
                    </linearGradient>
                  </defs>
                </svg>
                {/* Number in center */}
                <div style={{
                  position: 'absolute',
                  top: 0,
                  left: 0,
                  width: '100%',
                  height: '100%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  fontSize: 48,
                  fontWeight: 'bold',
                  fontFamily: 'Helvetica, Arial, sans-serif',
                  color: '#FFFFFF',
                }}>
                  {secondsLeft}
                </div>
              </div>
            );
          })()}
        </div>
      </Sequence>

      {/* Green screen flash when answer "A" is revealed */}
      <Sequence from={answerRevealFrame} durationInFrames={Math.floor(0.3 * fps)}>
        <div style={{
          position: 'absolute',
          inset: 0,
          backgroundColor: 'rgba(0, 255, 0, 0.25)',
          opacity: interpolate(
            frame - answerRevealFrame,
            [0, 3, Math.floor(0.3 * fps)],
            [0, 1, 0],
            { extrapolateRight: 'clamp' }
          ),
          pointerEvents: 'none',
          zIndex: 50,
        }} />
      </Sequence>
    </AbsoluteFill>
  );
};
